[tool.ruff]
line-length = 120

[tool.ruff.mccabe]
max-complexity = 10

# imported but unused
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
doctest_optionflags = "NORMALIZE_WHITESPACE"
