[tool.ruff]
line-length = 120
extend-select = ["RUF100"]

# imported but unused
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
doctest_optionflags = "NORMALIZE_WHITESPACE"
