# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Documentation and doctests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        minizinc_image: [
          "https://github.com/MiniZinc/MiniZincIDE/releases/download/2.6.4/MiniZincIDE-2.6.4-x86_64.AppImage",
          "https://github.com/MiniZinc/MiniZincIDE/releases/download/2.5.0/MiniZincIDE-2.5.0-x86_64.AppImage",
        ]

    env:
      MINIZINC_URL: ${{ matrix.minizinc_image }}
    steps:
    - uses: actions/checkout@v2
    - name: Add bin/ to PATH
      run: |
        mkdir -p ${{ github.workspace }}/bin
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
    - name: Cache MiniZinc
      id: cache-minizinc
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/bin/minizinc
        key: ${{ env.MINIZINC_URL }}
    - name: Download MiniZinc
      if: steps.cache-minizinc.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install libfuse2
        sudo curl -o ${{ github.workspace }}/bin/minizinc -L $MINIZINC_URL
        sudo chmod +x ${{ github.workspace }}/bin/minizinc
        minizinc --version
    - name: Cache dev modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-dev-${{ hashFiles('**/requirements.txt', '**/requirements_dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check minizinc version
      run: |
        minizinc --version
    - name: Install nox
      run: |
        pip install nox
    - name: Doc tests
      run: |
        nox -s doc --reuse-existing-virtualenvs
